# Generated by Django 5.1.4 on 2025-01-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
