# Generated by Django 5.1.4 on 2024-12-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='idle_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
