# Generated by Django 5.1.4 on 2025-01-02 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0002_alter_leavebalance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveRequest',
            new_name='Leave',
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
