# Generated by Django 5.1.4 on 2024-12-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0004_featureusage_project_systemerror_systemusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsupportticket',
            name='subject',
            field=models.CharField(default='No subject', max_length=100),
        ),
    ]
