# Generated by Django 5.1.4 on 2025-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0004_break_reason_for_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='break',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
