# Generated by Django 5.1.4 on 2025-01-03 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0004_timesheet_approval_status_timesheet_manager_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', through='aps.ProjectAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
