# Generated by Django 5.1.4 on 2025-01-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0005_alter_break_end_time_alter_break_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='break',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
