# Generated by Django 5.1.4 on 2025-01-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0005_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientparticipation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
