# Generated by Django 5.1.4 on 2025-01-05 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0005_project_users'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('panno', models.CharField(default='UNKNOWN', max_length=20)),
                ('job_description', models.CharField(default='Not Assigned', max_length=100)),
                ('employment_status', models.CharField(max_length=50)),
                ('emergency_contact_address', models.TextField(default='Unknown')),
                ('emergency_contact_primary', models.CharField(default='0000000000', max_length=15)),
                ('emergency_contact_name', models.CharField(default='Unknown', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('work_location', models.CharField(max_length=100, null=True)),
                ('contact_number_primary', models.CharField(blank=True, default='0000000000', max_length=15, null=True)),
                ('personal_email', models.EmailField(default='not_provided@example.com', max_length=254)),
                ('aadharno', models.CharField(blank=True, default='UNKNOWN', max_length=12, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
