# Generated by Django 5.1.4 on 2025-01-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0006_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('suspended', 'Suspended')], default='active', max_length=50),
        ),
    ]
