# Generated by Django 5.1.4 on 2025-01-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0006_clientparticipation_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='role_in_project',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Employee', 'Employee'), ('Support', 'Support'), ('Appraisal', 'Appraisal'), ('Tester', 'Tester')], default='Employee', max_length=50),
        ),
    ]
