# Generated by Django 5.1.4 on 2025-01-06 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0007_alter_userdetails_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='panno',
            field=models.CharField(default='UNKNOWN', max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid PAN number format.', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='work_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
