# Generated by Django 5.1.4 on 2024-12-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0008_attendance_clock_in_time_attendance_clock_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Pending', 'Pending'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
