# Generated by Django 5.1.4 on 2025-01-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0008_remove_project_client_project_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='role_in_project',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Employee', 'Employee'), ('Support', 'Support'), ('Appraisal', 'Appraisal'), ('QC', 'QC')], default='Employee', max_length=50),
        ),
    ]
