# Generated by Django 5.1.4 on 2025-01-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0009_remove_userdetails_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', '--------'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='Unknown', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='contact_number_primary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emergency_contact_primary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('', '--------'), ('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('suspended', 'Suspended')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '--------'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='panno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
