# Generated by Django 5.1.4 on 2025-01-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0009_remove_message_chat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserComplaint',
        ),
    ]
