# Generated by Django 5.1.4 on 2025-01-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0009_alter_projectassignment_role_in_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.RemoveField(
            model_name='projectassignment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectassignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientParticipation',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectAssignment',
        ),
    ]
