# Generated by Django 5.1.4 on 2025-01-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0010_alter_userdetails_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='aadharno',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
