# Generated by Django 5.1.4 on 2025-01-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0011_project_clientparticipation_projectassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientparticipation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_participations', to='aps.project'),
        ),
    ]
