# Generated by Django 5.1.4 on 2024-12-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0011_alter_attendance_status_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
