# Generated by Django 5.1.4 on 2025-01-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0011_alter_userdetails_aadharno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('', '--------'), ('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('suspended', 'Suspended'), ('absconding', 'Absconding')], max_length=50, null=True),
        ),
    ]
