# Generated by Django 5.1.4 on 2025-01-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0012_alter_clientparticipation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('On Hold', 'On Hold')], max_length=20),
        ),
    ]
