# Generated by Django 5.1.4 on 2025-01-07 10:09

import aps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0013_support_delete_itsupportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='ticket_id',
            field=models.CharField(default=aps.models.generate_ticket_id, max_length=36, unique=True),
        ),
    ]
