# Generated by Django 5.1.4 on 2025-01-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0014_project_updated_at_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
