# Generated by Django 5.1.4 on 2025-01-17 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0014_globalupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalupdate',
            options={'permissions': [('manage_globalupdate', 'Can manage Global Updates')]},
        ),
        migrations.AddField(
            model_name='globalupdate',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
