# Generated by Django 5.1.4 on 2025-01-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0015_alter_globalupdate_options_globalupdate_managed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
