# Generated by Django 5.1.4 on 2025-01-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0016_attendance_leave_request_leaverequest_approver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='emp_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='emp_id',
            new_name='user',
        ),
    ]
