# Generated by Django 5.1.4 on 2025-01-18 05:26

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0016_usersession_ip_address_usersession_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='idle_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
